// Auto-generated by idl-c.tiri

FDEF maGetTimeZoneInfo[] = { { "ZoneID", FD_STR }, { "StartYear", FD_INT }, { "EndYear", FD_INT }, { "TimeZoneInfo:Info", FD_PTR|FD_STRUCT|FD_ALLOC|FD_RESULT }, { 0, 0 } };

static const struct MethodEntry clTimeMethods[] = {
   { AC(-1), (APTR)TIME_SetTime, "SetTime", 0, 0 },
   { AC(-2), (APTR)TIME_GetTimeZoneInfo, "GetTimeZoneInfo", maGetTimeZoneInfo, sizeof(struct pt::GetTimeZoneInfo) },
   { AC::NIL, 0, 0, 0, 0 }
};

static const struct ActionArray clTimeActions[] = {
   { AC::Query, TIME_Query },
   { AC::Refresh, TIME_Refresh },
   { AC::NIL, nullptr }
};

