// Auto-generated by idl-c.tiri

static const struct FieldDef clNetServerNSF[] = {
   { "SSL", 0x00000001 },
   { "Synchronous", 0x00000002 },
   { "LogAll", 0x00000004 },
   { "Broadcast", 0x00000008 },
   { "Udp", 0x00000010 },
   { "DisableServerVerify", 0x00000020 },
   { "MultiConnect", 0x00000040 },
   { "KeepAlive", 0x00000080 },
   { nullptr, 0 }
};

static const struct FieldDef clNetServerNTC[] = {
   { "Disconnected", 0x00000000 },
   { "Resolving", 0x00000001 },
   { "Connecting", 0x00000002 },
   { "Handshaking", 0x00000003 },
   { "Connected", 0x00000004 },
   { "Multistate", 0x00000005 },
   { nullptr, 0 }
};

FDEF maDisconnectClient[] = { { "Client", FD_OBJECTPTR }, { 0, 0 } };
FDEF maDisconnectSocket[] = { { "Socket", FD_OBJECTPTR }, { 0, 0 } };

static const struct MethodEntry clNetServerMethods[] = {
   { AC(-7), (APTR)NETSERVER_DisconnectClient, "DisconnectClient", maDisconnectClient, sizeof(struct ns::DisconnectClient) },
   { AC(-8), (APTR)NETSERVER_DisconnectSocket, "DisconnectSocket", maDisconnectSocket, sizeof(struct ns::DisconnectSocket) },
   { AC::NIL, 0, 0, 0, 0 }
};

static const struct ActionArray clNetServerActions[] = {
   { AC::Free, NETSERVER_Free },
   { AC::Init, NETSERVER_Init },
   { AC::NewObject, NETSERVER_NewObject },
   { AC::Read, NETSERVER_Read },
   { AC::Write, NETSERVER_Write },
   { AC::NIL, nullptr }
};

